music/urls.py
from django.urls import path
from .import views
app_name='music'
urlpatterns = [
    # /music1
    path('', views.IndexView.as_view(), name='index'),
    #register
    path('register/', views.UserFormView.as_view(), name='register'),

    #/music/albumid
    path('<pk>/', views.DetailsView.as_view(), name='details'),

    #music/album/add
    path('album/add/', views.AlbumCreate.as_view(), name='album-add'),

    # music/album/update
    path('album/<pk>/', views.AlbumUpdate.as_view(), name='album-update'),
    # music/album/add
    path('album/<pk>/delete/', views.AlbumDelete.as_view(), name='album-delete'),

]

website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=250)
    genre_models = models.CharField(max_length=250)
    album_logo = models.FileField()
    def get_absolute_url(self):
        return reverse('music:details', kwargs={'pk':self.pk})
    def  __str__(self):
        return self.album_title+'-'+self.artist+'-'


class song (models.Model):
    album = models.ForeignKey(Album, on_delete = models.CASCADE)
    file_type = models.CharField(max_length=25)
    song_title = models.CharField(max_length=250)
    is_favourite= models.BooleanField(default=False)
    def  __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):

    password= forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model= User
        fields = ['username','email','password']

music/views.py
from django.views import generic
from .models import Album
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
from django.views.generic import View
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from .forms import UserForm


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailsView(generic.DetailView):
    model = Album
    template_name = 'music/details.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre_models', 'album_logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre_models', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class UserFormView(View):
    form_class=UserForm
    template_name='music/registration_form.html'

    #display blank form
    def get(self,request):
        form = self.form_class(None)
        return render(request, self.template_name,{'form':form})
    #process from data
    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            #normalize data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #authenticate
            user = authenticate(username=username,password=password)

            if user is not None :
                if user.is_active:
                    login(request,user)
                    return redirect('music:details')
        return render(request,self.template_name,{'form':form})

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>


    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style1.css'  %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <meta charset="UTF-8">
    <title>{% block title %}bhai log{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">


        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="{% url 'music:index' %}">bhai log</a>
        </div>
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums
                    </a>

                </li>
                <li class="">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Songs
                    </a>

                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input class="form-control" type="text" name="q" value="">


                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Albums
                    </a>

                </li>
                <li class="">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                    </a>

                </li>
            </ul>

        </div>


    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/details.html
{% extends 'music/base.html' %}
{% block body %}
{% block title %}Album title{% endblock %}
<h1>{{album.album_title  }}</h1>
<h3>{{ album.artist }}</h3>
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action=""method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <h3>{{ song.song_title }}</h3>


    {% endfor %}


</form>

    <a href="{% url 'music:details' album.id %}">
        <img src="{{ album.album_logo.url }}" class="img-responsive">
    </a>

{% endblock %}

music/templates/music/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text danger small">{{ field.errors }}</span>
        </div>
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>

    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block body %}

<ul class="try">

    {% for album in all_albums %}
    <li><a href="{% url 'music:details' album.id %}">{{ album.album_title }}-{{ album.artist }}</a></li>
        &nbsp;
        <form action="{% url 'music:album-delete' album.id %}" method="post" style="display:inline;">
            {% csrf_token %}
            <input type="hidden" name="album_id" value="{{ album.id }}"/>
            <button type="submit" class="btn btn-default btn-sum">
                <span class="glyphicon glyphicon-trash"></span>
            </button>
        </form>
    {% endfor %}

</ul>
{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}register{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
{% endblock %}